<?php

use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Illuminate\Http\Response;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\MessageBag;


function FileReads($value) {
    /**
     * file generated by laravel by default
    **/
    dd($value);
}
