<?php

namespace App\Providers;

use App\Models\User;
use App\Observers\UserObserver;
use Facade\FlareClient\Stacktrace\File;
use Illuminate\Support\ServiceProvider;
use App\Traits\FastTrait;

class AppServiceProvider extends ServiceProvider
{
    use FastTrait;
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        /**
         * file generated by laravel
         * */
        $this->filesTrait();
        User::observe(UserObserver::class);
    }
}
